### ISSUE TITLE
How to use vscode predefined placeholder/env variables in plugin's settings?

### ISSUE THREAD

**Issue by 0ptimista** [Lencerf/vscode-beancount#103]
I have a virtual env in `$HOME/beanshop/.venv/`

When I try to use env variables in `Python3 Path` configuration, it's not working either `${userHome}` or `${env:HOME}` described in [VS Code Reference](https://code.visualstudio.com/docs/editor/variables-reference)
![CleanShot 2024-05-17 at 11 04 16@2x](https://github.com/Lencerf/vscode-beancount/assets/115677077/1b702212-3838-4783-890b-b89d36b73770)

![CleanShot 2024-05-17 at 11 02 07@2x](https://github.com/Lencerf/vscode-beancount/assets/115677077/5d9e167d-e019-4ac2-a6ef-63875730b973)

Any ideas?

**Comment by mengqi92** [comment]
Try using `~`? The plugin will replace `~` with ${process.env.HOME} once it detects `~` in the path.

**Comment by 0ptimista** [comment]
> Try using `~`? The plugin will replace `~` with ${process.env.HOME} once it detects `~` in the path.

Thanks! `~` is worked!

**Comment by 0ptimista** [comment]
Problem perfectly solved!
