### ISSUE TITLE
Auto-completion of tags

### ISSUE THREAD

**Issue by zahanm** [Lencerf/vscode-beancount#16]
I wonder if we can make a simple change to have auto-complete pick up tags on transactions. ie `#trip-to-hawaii`

**Comment by Lencerf** [comment]
We first need to modify `beancheck.py` to collect tag information from beancount parser. After that we need to modify the function `provideCompletionItems` in `completer.ts` to provide tag completion list. We may also need to add `#` to `vscode.languages.registerCompletionItemProvider` in `extension.ts` such that `#` can trigger the completion.

I will do it later.
