### ISSUE TITLE
Account completion does not work with (some) unicode characters

### ISSUE THREAD

**Issue by nzp** [Lencerf/vscode-beancount#20]
Tried with south Slavic latin characters (ć, č, š, etc.) and also with (Serbian) cyrillic. It seems that the completion treats these characters as separators (parts before and after show up for completion). I guess the relevant regex isn't complete (from what I see in https://github.com/Lencerf/vscode-beancount/pull/19, didn't dig deeper)?

**Comment by lockjs** [comment]
I think theres a fairly easy fix for this. Could you provide some examples I can use to check I've understood your issue?

I'll update [#19](https://github.com/Lencerf/vscode-beancount/pull/19) assuming I can get the strings to match correctly

**Comment by nzp** [comment]
Great! Here are some examples.

Completion for, e.g. `Expenses:Potrepštine:Mačka:Hrana-za-mačku` first gives `Expenses:Potrep`, then `tine:Ma`, then `ka:Hrana-za-ma`, and finally `ku`. I'm also attaching how the account looks in syntax highlight. The non-ASCII characters in the set are: `š`, `đ`, `č`, `ć`, `ž` (I assume it would be the same with capitals, but haven't tried).

As for Cyrillic, nothing even get registered. E.g. for `Equity:Пример` there is no completion whatsoever.

HTH.
![image](https://user-images.githubusercontent.com/1195378/59622745-b609d200-9132-11e9-8746-8b949abaea52.png)

**Comment by nzp** [comment]
I can confirm that https://github.com/Lencerf/vscode-beancount/pull/19 resolved this issue, so I'm closing it. Thanks!
