### ISSUE TITLE
Auto-completion of payees and narrations can not match CJK characters

### ISSUE THREAD

**Issue by gnaish** [Lencerf/vscode-beancount#30]
If payees and narrations are CJK(Chinese, Japanese and Korean) characters, the auto-completion can not work.

For instance, if payee name is "鼎泰豐" , nothing pops up after typed 鼎

Thanks for your excellent work.

**Comment by Lencerf** [comment]
I tried resolving this issue by using `"` to trigger auto completion of payees and narrations. Please try the attached `beancount-0.4.3.vsix` to see if it works. 

To install it, refer to [Install from a VSIX](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix).

[beancount-0.4.3.vsix.zip](https://github.com/Lencerf/vscode-beancount/files/3640245/beancount-0.4.3.vsix.zip)

**Comment by gnaish** [comment]
Verified. This version works now~ Thanks.
