### ISSUE TITLE
Multi-file-ledger: vscode does not reflect "parent" files

### ISSUE THREAD

**Issue by Dr-Nuke** [Lencerf/vscode-beancount#33]
Setting:
A main ledger file A ("parent") that includes files files B and C (both "children") containing account openings and transactions.

When editing a child, syntax errors are highlighted whenever "bean-check PathToChild" throws an error.  Auto-completion does not work for accounts mentioned only in other children or the parent.

Could this be improved such that vscode is aware of the parent file A and all its children, B and C, when highlighting syntax errors and auto completing edits? Even if all files were in the same folder?

**Comment by SEIAROTg** [comment]
This has already been implemented. There is an option "Main Bean File" which allows you to override the path of entry file.

Automatic discovery of main file is not feasible as the current file could be included in multiple files.

**Comment by Dr-Nuke** [comment]
Thanks for the hint.
