### ISSUE TITLE
Support multiple main bean files

### ISSUE THREAD

**Issue by Akuukis** [Lencerf/vscode-beancount#37]
# Problem

How hard would it be to support multiple, unrelated ledgers each with multiple files? I have a use case where I write my personal and household ledgers in separately, but using the `"beancount.mainBeanFile"` I can select only one of them, while the other is simply ignored.

# Proposal
Expand config to support multiple main bean files
```json
{
    "beancount.mainBeanFile": [
        "personal/main.bean",
        "household/main.bean"
    ]
}
```

**Comment by Lencerf** [comment]
Hello! I currently have no plan to support multiple main bean files.

For your use case, I would suggest the following:
* For each `main.bean`, put it in a separate folder like `personal`, `household`.
* open each folder as a vscode workspace, and then open settings, switch to `Workspace` (not `User`, see https://code.visualstudio.com/docs/getstarted/settings), and then set `beancount.mainBeanFile` to `main.bean`.

After the two steps, you will have the following folders and files:
```
BeanFolder
├── household
│   ├── .vscode
│   │   └── settings.json
│   └── 2017.bean
└── personal
    ├── .vscode
    │   └── settings.json
    └── 2017.bean
```
In each `settings.json`, you should have `"beancount.mainBeanFile": "main.bean"`. Now if you switch your workspace between `household` and `personal`, this extension will automatically choose the corresponding main bean file.

**Comment by Akuukis** [comment]
Thanks, that's a straightforward workaround.

To clarify, in order to edit both personal and household in the same time, I need two VSCode windows open, right?

**Comment by Lencerf** [comment]
> To clarify, in order to edit both personal and household in the same time, I need two VSCode windows open, right?

Yes
