### ISSUE TITLE
Account autocompletion fails due to commodity price error.

### ISSUE THREAD

**Issue by dofine** [Lencerf/vscode-beancount#38]
Update: see https://github.com/Lencerf/vscode-beancount/issues/38#issuecomment-600419836.

Fold structure and workspace settings are
`{
    "beancount.mainBeanFile": "main.bean",
    "beancount.python3Path": "/Users/dufan/anaconda3/bin/python3"
}`

In `mean.bean` I have included all other beancount files. In `account.beancount` there are all `open` commands. But no account auto complete when editing other files, like `test.beancount`.

**Comment by Lencerf** [comment]
1. Do you mean that in previous versions, say 0.5.3, account autocompletion can work, but now it does not work?
2. What is the current version of your vscode? 1.43.0?
3. In main.bean, can you see account autocompletion?
4. Does autocompletion of narrations and payees work?
5. Can you please open OUTPUT (besides TERMINAL) and switch to Beancount to see what is the output? example:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/6895736/76881760-017f1700-6850-11ea-961f-188dab798767.png">

**Comment by dofine** [comment]
Hi, sorry to bother you. Not related to version. ( As I updated my beancount and plugin almost the same day, it's hard to find out.) 

It hangs here forever because I have a seperate `invest.beancount` file to record stock investment and price change, while some prices for a commodity are missing. 
![image](https://user-images.githubusercontent.com/440101/76925304-f988ab00-6913-11ea-9982-860c8e87bca1.png)
1. Directly run the command in terminal works. 
![image](https://user-images.githubusercontent.com/440101/76925464-82074b80-6914-11ea-8bef-282432205b9e.png)
2. Leave out the `invest.beancount` file, the plugin works as expected.

**Comment by Lencerf** [comment]
Can you please try this version 0.5.5? To install it, please see https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

[beancount-0.5.5.zip](https://github.com/Lencerf/vscode-beancount/files/4347093/beancount-0.5.5.zip)

The problem comes from `<unrealized_gains>` in the output. Since beancount does not provide a valid file path, to fix the problem, I just simply replace `<unrealized_gains>` by main bean file path.

**Comment by dofine** [comment]
0.5.5 Works. Thanks!
