### ISSUE TITLE
support account autocomplete in `balance`

### ISSUE THREAD

**Issue by Trim21** [Lencerf/vscode-beancount#39]
I'm not sure if I didn't trigger auto-completion or there is no such function(and I'm glad to implement it)?

**Comment by Lencerf** [comment]
There is such function:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/6895736/76992821-2fcd2700-6922-11ea-93f2-860ee05e71c8.png">

Do you mean that on your machine auto-completion of accounts works in postings but not in `balance`?

**Comment by Trim21** [comment]
yes, only viscose word based autocompletion



------------------ Original ------------------

**Comment by Lencerf** [comment]
Account auto-completion is implemented here:

https://github.com/Lencerf/vscode-beancount/blob/87bdf4dc973151742b7b3987658bed5518794c28/src/completer.ts#L252

Currently I have no clue why it does not work. I appreciate it if you can help resolve this issue.

**Comment by Trim21** [comment]
I can trigger such autocompletion like the image you posted: account in same file are suggested.
But not the account from main file, like auto completion in transition. So I guess it may just be word based suggestions instead of autocompletion suggested by extension.

I'll do some more research.
