### ISSUE TITLE
Publishing on Open VSX

### ISSUE THREAD

**Issue by mpolanski** [Lencerf/vscode-beancount#47]
Hello!

Would you mind publishing your extension on [Open VSX registry](https://open-vsx.org/)? Packages such as [code](https://www.archlinux.org/packages/community/x86_64/code/) or [vscodium](https://github.com/VSCodium/vscodium) can't use Visual Studio Marketplace, because its [Terms of Use](https://aka.ms/vsmarketplace-ToU) restricts it only to Microsoft's products.

Here are the [publishing instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). It comes down to adding `ovsx publish` command in addition to your normal `vsce publish`.

Thanks for making this extension!

**Comment by Lencerf** [comment]
Published: https://open-vsx.org/extension/Lencerf/beancount

Please also help test if it works. Thank you!

**Comment by mpolanski** [comment]
Works without a problem :+1:
