### ISSUE TITLE
Implement region markers for code folding

### ISSUE THREAD

**Issue by gilbertginsberg** [Lencerf/vscode-beancount#5]
Would it be possible to implement region markers for code folding (and thus better beancount doc organization) in VS Code? 

For instance: https://code.visualstudio.com/updates/v1_17#_editor

**Comment by Lencerf** [comment]
I do not quiet understand what is your need. The syntax of beancount is simple and I do not know where we will need to fold codes. Can you provide an example of codes needed to be folded? Also what do the codes look like after they are folded? Thank you.

**Comment by gilbertginsberg** [comment]
What I had in mind was the following, but specifically for the beancount language:

![screen shot 2017-12-25 at 11 05 13 am](https://user-images.githubusercontent.com/4500679/34341331-86aafad4-e963-11e7-8495-cc31df406601.png)

To allow you to structure your beancount file a la "org-mode." One example where code folding might be of use is if you break down transactions, say, by Country. And you want to keep them separate, in their own country list. After folding, it might look something 

![screen shot 2017-12-25 at 11 15 24 am](https://user-images.githubusercontent.com/4500679/34341412-f6d3f2ec-e964-11e7-9cb3-3432c29d663b.png)
like this:

All that said, I actually found a way to use VSCode's built-in folding functionality to make this work.

Thanks for hearing me out, and thanks for the extension.

**Comment by vloris** [comment]
Sorry to comment on a closed issue, but I'm really curious how you got it to work with VSCode's built-in folding without a change to the beancount plugin?

**Comment by gilbertginsberg** [comment]
@vloris: VS Code uses indentation to define folding regions. VS Code explains it as such:

"Folding regions are evaluated based on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent." More here: https://code.visualstudio.com/docs/editor/codebasics#_folding

So, say you have something like this:

![screen shot 2018-01-02 at 12 05 17 pm](https://user-images.githubusercontent.com/4500679/34492387-5921817a-efb5-11e7-9664-ae56a49f73b9.png)

If you move your mouse over the gutter on the left and click the square with the ... in the center, that'll fold the region. If you click the top one (the one next to "Some header), everything below will be folded:

![screen shot 2018-01-02 at 12 05 44 pm](https://user-images.githubusercontent.com/4500679/34492462-acee94dc-efb5-11e7-91f2-32dc636dbf1b.png)

Or if you click the second one, only what's below will be folded:

![screen shot 2018-01-02 at 12 05 52 pm](https://user-images.githubusercontent.com/4500679/34492501-df6d82d8-efb5-11e7-89a2-7da554885487.png)

Which means, you can use this to your benefit how you please whilst still abiding by the syntax of beancount.

If you're aiming for more nested regions, you could do something like this which is a bit hacky but effective nonetheless:

![screen shot 2018-01-02 at 12 10 54 pm](https://user-images.githubusercontent.com/4500679/34492546-177ce89e-efb6-11e7-9f97-3d8eb967e20b.png)

You can comment out the `— US` which beancount doesn't recognize, while at the same time taking advantage of VS Code's built-in folding.  

I'm sure there might be better ways to handle this, but for now, this kind of code folding is sufficient for my purposes. Cheers.

**Comment by akshaysalunke13** [comment]
I'm unable to achieve folding like this in my accounts file.
<img width="315" alt="image" src="https://github.com/Lencerf/vscode-beancount/assets/2255284/1e73a5c9-4651-493d-a5b5-33df986c9d76">
