### ISSUE TITLE
金额自动对齐时，无法将中文字符识别为2个字符

### ISSUE THREAD

**Issue by ZinngRui** [Lencerf/vscode-beancount#56]
您好！您的插件非常棒，感谢您的分享！

我在使用中发现，账户信息是纯英文时，对齐的很完美，但是中英文混合的账户，无法对齐。

<a href="url"><img src="https://i.loli.net/2021/06/24/Ff5G3jhKDESX1qu.png" align="center" height="70%"  width="70%"  ></a>

我使用的是严格的等宽字体，2个英文字母（不区分大小写）宽度 = 1个中文宽度。
经过我的测试，证实formatter插件没有将1个中文的宽度和1个英文字母的宽度进行区分，两者的宽度被视为是一样的。

以下这两行字符数是一样多，格式化后是这样：

<a href="url"><img src="https://i.loli.net/2021/06/24/YFtBfg6DC247RGr.png" align="center" height="70%"  width="70%"  ></a>

1个中文的宽度，实际占用了2个英文字母的空间。第一行一共有8个中文，我们在第二行补上8个英文字母后，金额就对齐了：

<a href="url"><img src="https://i.loli.net/2021/06/24/uJV78QWahDoGbiO.png" align="center" height="70%"  width="70%"  ></a>

[参考字体](https://github.com/be5invis/Sarasa-Gothic/releases)

参考代码：
` Expenses:食品烟酒:烟酒:酒类                                          500.00 CNY`
` Expenses:abcd:ab:ab                                          600.00 CNY`
` abcdababExpenses:abcd:ab:ab                                          600.00 CNY`

我的个人代码能力很差，希望您能在有空的时候，解决一下这个问题。
万分感谢！

**Comment by Lencerf** [comment]
你好，Pull Request #55 应当已经解决问题，敬请测试，不过注意需要特定字体支持，比如[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)。

**Comment by ZinngRui** [comment]
> 你好，Pull Request #55 应当已经解决问题，敬请测试，不过注意需要特定字体支持，比如[更纱黑体](https://github.com/be5invis/Sarasa-Gothic)。

非常感谢！已经使用。效果很好！祝您万事如意！
