### ISSUE TITLE
Can I use relative path on beancount.python3path

### ISSUE THREAD

**Issue by whusnoopy** [Lencerf/vscode-beancount#58]
As I worked on a macOS and a WSL, the full `beancount.python3path` are `/Users/yewen/.virtualenvs/bc/bin/python` and `/home/yewen/.virtualenvs/bc/bin/python`, I want to set the path to `~/.virtualenvs/bc/bin/python` then I can sync project settings between macOS and WSL

But it doesn't works on WSL, the output on absolutely path and relative path are

```
try finding a valid bean file...user specified a main bean file with a relative path...
running /home/yewen/.virtualenvs/bc/bin/python /home/yewen/.vscode-server/extensions/lencerf.beancount-0.7.0/pythonFiles/beancheck.py,/home/yewen/workspace/personal-beancount/main.bean,--payeeNarration to refresh data...
try finding a valid bean file...user specified a main bean file with a relative path...
Data refreshed.
try finding a valid bean file...user specified a main bean file with a relative path...
running ~/.virtualenvs/bc/bin/python /home/yewen/.vscode-server/extensions/lencerf.beancount-0.7.0/pythonFiles/beancheck.py,/home/yewen/workspace/personal-beancount/main.bean,--payeeNarration to refresh data...
error: Error: spawn ~/.virtualenvs/bc/bin/python ENOENT
```

and the `beancount.favaPath` works on relative path, the output are

```
try finding a valid bean file...user specified a main bean file with a relative path...
executed [~/.virtualenvs/bc/bin/fava -H 127.0.0.1 "/home/yewen/workspace/personal-beancount/main.bean"]
```

**Comment by whusnoopy** [comment]
作者应该是中文使用者，就不用蹩脚的英文来沟通了

问题应该是在 https://github.com/Lencerf/vscode-beancount/blob/5e40823e58d204b79e95d0bd36bb8929a219ef2b/src/utils.ts#L9 这里的 `child_process.spawn`，问了下朋友，解释是我这个 `~` 只是 `alias` 并不是相对路径，解决办法是包一层 `sh -c cmd` 来做，而需要跨平台的话，先判断一下 `os.platform === 'win32'` 来决定使用 `cmd -c` 还是 `sh -c`

对 VSCode 的插件调试测试机制不熟悉，还做不到直接给 PR，先记录信息在这里吧

**Comment by bruce3x** [comment]
hi 我的项目结构长这样
```
.
├── .vscode
│  └── settings.json
├── venv          👈 virtualenv
├── account
├── beans
│  └── 202201.bean
└── main.bean

```

virtualenv 创建在项目中，这么配置会有问题 👀
```json
{
    "beancount.python3Path": "venv/bin/python3",
    "beancount.favaPath": "venv/bin/fava"
}
```

还是报这个错误：
```
error: Error: spawn venv/bin/python3 ENOENT
```

@Lencerf @whusnoopy  有什么办法吗 

thanks
