### ISSUE TITLE
'Auto-completion of account names'  faile as below.

### ISSUE THREAD

**Issue by kklod** [Lencerf/vscode-beancount#67]
![image](https://user-images.githubusercontent.com/50442661/145744853-a5d5b699-1026-42cf-a7c0-dab476c5ffb3.png)

**Comment by papageno** [comment]
I'm encountering the same issue. Sometimes it works but mostly it doesn't.

I'm using VSCode 1.63.0 with GitHub Copilot turned on. It worked perfectly before the recent 1.63.0 VSCode update.

**Comment by floatingheads** [comment]
Same exact issue and reason (VS Code 1.63.0 is when the issue started) as @papageno

**Comment by papageno** [comment]
This issue seems to have worked well again!

**Comment by plainliu** [comment]
Same issue in VSCode 1.63.1, but disappeared after VSCode update to 1.63.2 . It seems to be VSCode's issue.
