### ISSUE TITLE
Adding an outline or SymbolProvider

### ISSUE THREAD

**Issue by isometimescode** [Lencerf/vscode-beancount#72]
I have a [version](https://github.com/isometimescode/vscode-beancount/tree/symbolprovider) of an outline using headers and the nested header. This is what it looks like on the `bean-example` data, with warnings and errors displaying on the side:
![screenshot](https://user-images.githubusercontent.com/7094373/171746934-4e2d8dc9-ca47-42e5-bf6e-fdec0e498023.jpg)

This is similar to the outline noted in #64, and I had attempted another one for #25, but I don't use `;#region` folding as much as I use nested `*` and `**` for the headers.

I'm happy to submit a PR either way, depending on what other users need.

**Comment by tcpekin** [comment]
How should one install your fork? I want this exact functionality, but have installed vscode-beancount using the VSC "store", and not from source. Should I clone your repo and then look up how to install vscode extensions from source? Or is there a different way to do it? Thanks in advance.

**Comment by tcpekin** [comment]
I have installed this from your repo and it works great so far!

**Comment by Lencerf** [comment]
Merged. Thanks!
