### ISSUE TITLE
Add git tags/releases for 0.8.2, 0.9.0  

### ISSUE THREAD

**Issue by seltzered** [Lencerf/vscode-beancount#74]
I'm trying to incorporate this plugin into a prebuilt app (via yarn) and can't reference the latest version by git tag or github releases. Can you add tags/releases? I couldn't find an obvious way to do this via pull-request, but the following should do it:

`git tag -a v0.8.2 7f4649d7e9a79152691beab752dfd030ad15f270 -m "add version tag"`
`git tag -a v0.9.0 625437c6c57ba8913f1c216a2b04b2fe3a6d95cb -m "add version tag"`
`git push --tags` 

Thanks!

**Comment by seltzered** [comment]
More specifically, I'm requesting if there can be github releases for 0.8.2 and 0.9.1 such that it appears on https://github.com/Lencerf/vscode-beancount/releases as I'm trying to package this plugin within an Eclipse Theia app, which by default prefers downloading the `.vsix` file directly. 

Worst case I could try to script something together to download from 'Version History' from https://marketplace.visualstudio.com/items?itemName=Lencerf.beancount , as it provides a download but of a direct vsix file ( https://stackoverflow.com/questions/37071388/how-can-i-install-visual-studio-code-extensions-offline )

**Comment by Lencerf** [comment]
Done.

**Comment by seltzered** [comment]
Thanks, turns out I actually need the vsix file (which on github is there for 0.8.1 but not 0.8.2 or 0.9.0) but...but... it looks like the openvsx registry entry you have for vscode-beancount (https://open-vsx.org/extension/Lencerf/beancount) has a direct vsix link that works fine for running `yarn theia download:plugins` , so thanks again!
