### ISSUE TITLE
Invalid reference to unknown

### ISSUE THREAD

**Issue by Doslin** [Lencerf/vscode-beancount#76]
# 账户设置需要在单个 分拆开的 .bean 文件中再次引入，才不会提示错误，这个需要怎么解决呢？有什么好的办法吗
<img width="221" alt="image" src="https://user-images.githubusercontent.com/29807388/188294103-52dfab83-fa21-4c37-afab-55d18111997b.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/29807388/188294110-fae01145-0bb9-4543-ab14-0cf7fade3656.png">
账户设置需要在单个 分拆开的 .bean 文件中再次引入，才不会提示错误，这个需要怎么解决呢？有什么好的办法吗
<img width="417" alt="image" src="https://user-images.githubusercontent.com/29807388/188294115-a11b9896-736d-4011-8a53-b56af195294c.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/29807388/188294120-38ca4262-3a4f-44ca-8cea-31624ea7a54b.png">

**Comment by kklod** [comment]
请问你是怎么解决的？

**Comment by jokerlin** [comment]
> 请问你是怎么解决的？

如上图所示，在vscode setting.json 加上 `"beancount.mainBeanFile":"main.bean"`
