### ISSUE TITLE
Feature request: open file from the include directive by clicking on it

### ISSUE THREAD

**Issue by Ev2geny** [Lencerf/vscode-beancount#79]
It would be nice if it would be possible to directly open (or directly go to) the file, specified by the `include` directive, when navigating through the main file.

**Comment by mengqi92** [comment]
Hello @Ev2geny, the feature has been provided with PR #99 and released in v0.11.0, please verify and close the issue, thanks!

**Comment by Ev2geny** [comment]
@mengqi92,  yes, I confirm it works! Fantastic!
Thank you very much!
